window.projectData = [
  {
    no: 1,
    name: "홍길동",
    phone: "010-1234-5678",
    address: "서울 강남구 역삼동",
    item: "포도",
    status: "예정",
    pnu: "",
    jimok: "",
    area: "",
    memo: [],
  },
  {
    no: 2,
    name: "이순신",
    phone: "010-2345-6789",
    address: "부산 해운대구",
    item: "사과",
    status: "완료",
    pnu: "",
    jimok: "",
    area: "",
    memo: [],
  },
];
